{{
const date = new Date();
const startDate = date.toISOString().split('T')[0] + 'T00:00:00.000Z';
const endDate = date.toISOString().split('T')[0] + 'T23:59:59.999Z';
exports.startDate = startDate;
exports.endDate = endDate;
}}

GET http://localhost:3000/posts/2?limit=1&page=1&startDate={{startDate}}&endDate={{endDate}}