POST http://localhost:3000/posts 
Content-Type: application/json

{
    "title": "Title one",
    "slug": "title-one-7",
    "content": "Content one",
    "postType": "post",
    "status": "draft",
    "metaOptions": 
        {
            "metaValue": "{\"key\":\"description-2\",\"value\":\"Description one\"}"
        }
    ,
    "tags": [1],
    // "schema": "{}",
    "image": "https://example.com/image.jpg",
    "authorId": 1
    }