POST http://localhost:3000/posts 
Content-Type: application/json

{
    "title": "Title one",
    "slug": "title-one-1-2",
    "content": "Content one",
    "postType": "post",
    "status": "draft",
    "metaOptions": 
        {
            "metaValue": "{\"key\":\"description-2\",\"value\":\"Description one\"}"
        }
    ,
    // "tags": ["tag1", "tag2"],
    // "schema": "{}",
    "image": "https://example.com/image.jpg"
    }