POST http://localhost:3000/users/create-many  
Content-Type: application/json
{"users":[
  {
    "firstName": "John",
    "email": "jasdsaohn.sdfsdf@example.com",
    "password": "strong@Password123"
  },
  {
    "firstName": "Jane",
    "email": "jasdasdsane.doe@fdsfdd.com",
    "password": "strong@Password123"
  }
]}